name: 'Client SDK Test Report'
on:
  workflow_run:
    workflows: ['Build and Test Client SDK']  # runs after CI workflow
    types:
      - completed
    branches:
      - master
      - FeatureIntegration
      - FeatureIntegration/**

jobs:

  report:
    name: "Generate Test Reports"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os-moniker:
          - 'Win'

        dotnet-moniker:
          - 'NetCore3.1'
          - 'Net6'
          - 'NetFx4.6'

        build-config:
          - 'Debug'
          - 'Release'

        include:
          - dotnet-moniker: 'NetCore3.1'
            dotnet-version: '3.1.x'
            framework: netcoreapp3.1

          - dotnet-moniker: 'Net6'
            dotnet-version: '6.0.x'
            framework: net6.0

          - dotnet-moniker: 'NetFx4.6'
            dotnet-version: '4.6.2'
            framework: net462

          - os-moniker: Win
            os-specifier: windows-latest
    
    steps:
      - name: Unit tests ${{matrix.os-moniker}}/${{matrix.dotnet-moniker}}/${{matrix.build-config}}
        uses: dorny/test-reporter@v1.5.0
        with:          
          artifact: TestResults_Unit_${{matrix.os-moniker}}_${{matrix.dotnet-moniker}}_${{matrix.build-config}}
          name: TestReport Unit ${{matrix.os-moniker}}/${{matrix.dotnet-moniker}}/${{matrix.build-config}}
          path: '*.trx'
          reporter: dotnet-trx
          max-annotations: '50'